"""cpusim backend — emit a CPU simulator harness + sweep config.

Given a Spec, produces:
    build/cpusim/simulate.py          — driver with step function stub
    build/cpusim/sweep.json           — grid + seeds config
    build/cpusim/run_sweep.sh         — executable sweep runner

The simulator stepper consumes the spec's `protocol.step_compose`
ordering and the substep inline expressions to form a Python-native
step function. For v0.3 the step function is a stub that users fill
in; v0.4 will auto-derive from inline_python fields.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


SIMULATE = '''\
"""Auto-generated by telos from a declarative spec.

Protocol: {name}
Step composition: {steps}
"""
from __future__ import annotations
import dataclasses
import json
from pathlib import Path


@dataclasses.dataclass
class State:
    W: int
{state_fields}


def step(state: State, ack: dict) -> State:
    """Apply the protocol's step composition to `state` under `ack`.

    telos v0.3: stub — users fill in each substep's Python body in a
    sibling `steps.py` and compose them here. v0.4 auto-derives.
    """
    return state


def simulate(W: int, B: int, D: int, schedule, filter_kind: str = "{default_filter}") -> dict:
    """Run a single trace, return verdict."""
    state = State(W=W{init_kwargs})
    for ack in schedule:
        state = step(state, ack)
    return dataclasses.asdict(state)


if __name__ == "__main__":
    import sys
    cfg = json.loads(Path(sys.argv[1]).read_text())
    rows = []
    for B in cfg["B_grid"]:
        for D in cfg["D_grid"]:
            for seed in range(cfg["seeds"]):
                # Schedule generation: deterministic in seed.
                schedule = [{{"delivered": 1, "wall_clock": float(D)}}
                            for _ in range(60)]
                v = simulate(cfg["W"], B, D, schedule)
                rows.append({{"B": B, "D": D, "seed": seed, **v}})
    out = Path(cfg["out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(rows, indent=2))
    print(f"wrote {{out}} ({{len(rows)}} rows)")
'''


# Shim emitted when `cpu_sim.reference_python` is set in the spec.
# Delegates step() and simulate() to the user-registered reference module
# instead of running the v0.3 stub. The shim is runnable by
# `python3 simulate.py sweep.json` exactly like the stub version, so
# telos verify's "run the cpu_sim backend" path works uniformly.
SIMULATE_SHIM = '''\
"""Auto-generated by telos from a declarative spec.

Protocol: {name}
Step composition: {steps}

This is a SHIM — the spec's `verifiers.cpu_sim.reference_python` points
at a user-maintained module that supplies the real step function. This
shim imports + delegates to it, so `telos verify` can actually run the
simulator instead of reporting "outlined / user-supplied".
"""
from __future__ import annotations
import importlib
import importlib.util
import json
import sys
import time
from pathlib import Path

# Resolve the reference-python path: try (a) as a module name, (b) as a
# file-path relative to the spec-containing repo root, (c) as an
# absolute file-path. Fail loud if none work.
_REF_TARGET = {reference_python!r}


def _load_reference():
    # (a) Sibling-file form: the reference was copied next to simulate.py
    #     by compile_cpusim — handles the portable, self-contained case.
    here = Path(__file__).resolve().parent
    sibling = here / _REF_TARGET
    if sibling.exists():
        target_path = sibling
    else:
        # (b) Module form (e.g. "mypkg.my_sim")
        if "/" not in _REF_TARGET and _REF_TARGET.endswith(".py") is False:
            try:
                return importlib.import_module(_REF_TARGET)
            except ImportError:
                pass

        # (c) File-path form with repo walk
        target_path = Path(_REF_TARGET)
        if not target_path.is_absolute():
            for parent in [here] + list(here.parents):
                cand = parent / _REF_TARGET
                if cand.exists():
                    target_path = cand
                    break
    if not target_path.exists():
        raise ImportError(
            f"telos cpu_sim shim: reference_python={{_REF_TARGET!r}} not "
            f"found as a module or as a file-path (tried repo walk)."
        )
    spec = importlib.util.spec_from_file_location(
        "_telos_cpu_sim_reference", str(target_path)
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load module from {{target_path}}")
    mod = importlib.util.module_from_spec(spec)
    # dataclass decorator needs the module to be in sys.modules before
    # exec so `sys.modules.get(cls.__module__).__dict__` works in its
    # type-resolution probe.
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


_ref = _load_reference()


def step(state, ack):
    return _ref.step(state, ack)


def simulate(W, B, D, schedule, filter_kind: str = "{default_filter}"):
    # Try the 5-arg form first; fall back to whatever signature the
    # reference module exposes.
    fn = getattr(_ref, "simulate", None)
    if fn is None:
        raise AttributeError(
            "reference module missing a `simulate(...)` entry point"
        )
    try:
        return fn(W=W, B=B, D=D, schedule=schedule, filter_kind=filter_kind)
    except TypeError:
        # Reference may use positional args or a different signature.
        return fn(W, B, D, schedule)


if __name__ == "__main__":
    cfg = json.loads(Path(sys.argv[1]).read_text())
    t0 = time.time()
    rows = []
    starvations = 0
    for B in cfg["B_grid"]:
        for D in cfg["D_grid"]:
            for seed in range(cfg["seeds"]):
                schedule = [{{"delivered": 1, "wall_clock": float(D)}}
                            for _ in range(60)]
                v = simulate(cfg["W"], B, D, schedule)
                rows.append({{"B": B, "D": D, "seed": seed, **v}})
                # Minimal starvation detector: pacing_rate collapsed to
                # non-positive at end of trace.
                if isinstance(v, dict) and v.get("pacing_rate", 1.0) <= 0:
                    starvations += 1
    out = Path(cfg["out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(rows, indent=2))
    elapsed = time.time() - t0
    print(
        f"cpu_sim: {{len(rows)}} cells across {{len(cfg['B_grid'])}}×"
        f"{{len(cfg['D_grid'])}}×{{cfg['seeds']}} in {{elapsed:.1f}}s; "
        f"{{starvations}} starvations"
    )
    # Exit non-zero if ANY cell starved — makes the verifier status
    # "failed" instead of "closed" when that happens. Zero starvations
    # => closed verdict.
    sys.exit(0 if starvations == 0 else 1)
'''


SWEEP_SH = '''\
#!/usr/bin/env bash
# Auto-generated by telos.
set -euo pipefail
python3 simulate.py sweep.json
'''


def compile_cpusim(spec: "Spec", out_dir: Path, spec_path: Path | None = None) -> list[Path]:
    """Compile the CPU-sim harness for a spec.

    Args:
        spec: parsed Spec.
        out_dir: directory to emit into (cpusim/ is created underneath).
        spec_path: path to the source YAML spec. When the spec sets
                   `cpu_sim.reference_python`, the reference module is
                   resolved relative to this spec's directory and copied
                   into the emitted build so the artefact is portable.
    """
    import shutil

    sim_dir = out_dir / "cpusim"
    sim_dir.mkdir(parents=True, exist_ok=True)

    if spec.verifiers.cpu_sim is None:
        return []

    # Synthesise state-field declarations + init kwargs.
    state_lines = []
    init_kw = []
    for f in spec.protocol.state:
        py_type = {"real": "float", "nat": "int"}.get(f.type, "object")
        default = "0.0" if py_type == "float" else "0"
        state_lines.append(f"    {f.name}: {py_type} = {default}")
        if f.name == "pacing_rate":
            # Start with positive pacing rate for positive-theorem tests.
            state_lines[-1] = f"    {f.name}: {py_type} = 1.0"

    sim_py = sim_dir / "simulate.py"
    if spec.verifiers.cpu_sim.reference_python:
        # v0.3.1: spec points at a hand-written Python simulator;
        # copy the reference next to simulate.py + emit a shim that
        # imports it by basename so the artefact is self-contained.
        ref_rel = spec.verifiers.cpu_sim.reference_python
        ref_src: Path | None = None
        if spec_path is not None:
            cand = (spec_path.parent / ref_rel).resolve()
            if cand.exists():
                ref_src = cand
        if ref_src is None:
            # Fallback: absolute or cwd-relative path
            cand = Path(ref_rel).resolve()
            if cand.exists():
                ref_src = cand
        if ref_src is None:
            raise FileNotFoundError(
                f"cpu_sim.reference_python={ref_rel!r} not found "
                f"(spec_dir={spec_path.parent if spec_path else None}, "
                "cwd-resolve failed too)"
            )
        ref_dst = sim_dir / "_reference.py"
        shutil.copyfile(ref_src, ref_dst)
        sim_py.write_text(SIMULATE_SHIM.format(
            name=spec.protocol.name,
            steps=" -> ".join(spec.protocol.step_compose) or "(empty)",
            reference_python="_reference.py",
            default_filter="bbrv3",
        ))
    else:
        sim_py.write_text(SIMULATE.format(
            name=spec.protocol.name,
            steps=" -> ".join(spec.protocol.step_compose) or "(empty)",
            state_fields="\n".join(state_lines) or "    # (no state fields)",
            init_kwargs="",
            default_filter="bbrv3",
        ))

    # Sweep config.
    grid = spec.verifiers.cpu_sim.grid
    B_grid = grid.get("B", [3, 4, 5])
    D_grid = grid.get("D", [1, 5])
    cfg = {
        "W": spec.verifiers.ebmc.concrete_tuple.get("W", 10)
              if spec.verifiers.ebmc else 10,
        "B_grid": B_grid,
        "D_grid": D_grid,
        "seeds": spec.verifiers.cpu_sim.seeds,
        "t_max_s": spec.verifiers.cpu_sim.t_max_s,
        "out": "sweep_results.json",
    }
    sweep_json = sim_dir / "sweep.json"
    sweep_json.write_text(json.dumps(cfg, indent=2))

    run_sh = sim_dir / "run_sweep.sh"
    run_sh.write_text(SWEEP_SH)
    run_sh.chmod(0o755)

    return [sim_py, sweep_json, run_sh]
