"""cpusim backend — emit a CPU simulator harness + sweep config.

Given a Spec, produces:
    build/cpusim/simulate.py          — driver with step function stub
    build/cpusim/sweep.json           — grid + seeds config
    build/cpusim/run_sweep.sh         — executable sweep runner

The simulator stepper consumes the spec's `protocol.step_compose`
ordering and the substep inline expressions to form a Python-native
step function. For v0.3 the step function is a stub that users fill
in; v0.4 will auto-derive from inline_python fields.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


SIMULATE = '''\
"""Auto-generated by telos from a declarative spec.

Protocol: {name}
Step composition: {steps}
"""
from __future__ import annotations
import dataclasses
import json
from pathlib import Path


@dataclasses.dataclass
class State:
    W: int
{state_fields}


def step(state: State, ack: dict) -> State:
    """Apply the protocol's step composition to `state` under `ack`.

    telos v0.3: stub — users fill in each substep's Python body in a
    sibling `steps.py` and compose them here. v0.4 auto-derives.
    """
    return state


def simulate(W: int, B: int, D: int, schedule, filter_kind: str = "{default_filter}") -> dict:
    """Run a single trace, return verdict."""
    state = State(W=W{init_kwargs})
    for ack in schedule:
        state = step(state, ack)
    return dataclasses.asdict(state)


if __name__ == "__main__":
    import sys
    cfg = json.loads(Path(sys.argv[1]).read_text())
    rows = []
    for B in cfg["B_grid"]:
        for D in cfg["D_grid"]:
            for seed in range(cfg["seeds"]):
                # Schedule generation: deterministic in seed.
                schedule = [{{"delivered": 1, "wall_clock": float(D)}}
                            for _ in range(60)]
                v = simulate(cfg["W"], B, D, schedule)
                rows.append({{"B": B, "D": D, "seed": seed, **v}})
    out = Path(cfg["out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(rows, indent=2))
    print(f"wrote {{out}} ({{len(rows)}} rows)")
'''


SWEEP_SH = '''\
#!/usr/bin/env bash
# Auto-generated by telos.
set -euo pipefail
python3 simulate.py sweep.json
'''


def compile_cpusim(spec: "Spec", out_dir: Path) -> list[Path]:
    """Compile the CPU-sim harness for a spec."""
    sim_dir = out_dir / "cpusim"
    sim_dir.mkdir(parents=True, exist_ok=True)

    if spec.verifiers.cpu_sim is None:
        return []

    # Synthesise state-field declarations + init kwargs.
    state_lines = []
    init_kw = []
    for f in spec.protocol.state:
        py_type = {"real": "float", "nat": "int"}.get(f.type, "object")
        default = "0.0" if py_type == "float" else "0"
        state_lines.append(f"    {f.name}: {py_type} = {default}")
        if f.name == "pacing_rate":
            # Start with positive pacing rate for positive-theorem tests.
            state_lines[-1] = f"    {f.name}: {py_type} = 1.0"

    sim_py = sim_dir / "simulate.py"
    sim_py.write_text(SIMULATE.format(
        name=spec.protocol.name,
        steps=" -> ".join(spec.protocol.step_compose) or "(empty)",
        state_fields="\n".join(state_lines) or "    # (no state fields)",
        init_kwargs="",
        default_filter="bbrv3",
    ))

    # Sweep config.
    grid = spec.verifiers.cpu_sim.grid
    B_grid = grid.get("B", [3, 4, 5])
    D_grid = grid.get("D", [1, 5])
    cfg = {
        "W": spec.verifiers.ebmc.concrete_tuple.get("W", 10)
              if spec.verifiers.ebmc else 10,
        "B_grid": B_grid,
        "D_grid": D_grid,
        "seeds": spec.verifiers.cpu_sim.seeds,
        "t_max_s": spec.verifiers.cpu_sim.t_max_s,
        "out": "sweep_results.json",
    }
    sweep_json = sim_dir / "sweep.json"
    sweep_json.write_text(json.dumps(cfg, indent=2))

    run_sh = sim_dir / "run_sweep.sh"
    run_sh.write_text(SWEEP_SH)
    run_sh.chmod(0o755)

    return [sim_py, sweep_json, run_sh]
