"""dafny backend — emit a Dafny 4.x module from a telos spec.

Given a Spec, produces:
    build/dafny/<Protocol>.dfy

With a self-contained module defining the state + substep functions
+ theorem signatures. Verifier containerised run happens at
`telos verify` time.

v0.2 minimal: types + substep placeholders + theorem lemma
skeletons. Inline_dafny expressions pass through.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


HEADER = '''\
// Auto-generated by telos from a declarative spec.
// Do NOT edit by hand; re-run `telos compile` to regenerate.
//
// Protocol: {name}
// Citation: {citation}
//
// Verify with the dafny-base container:
//   docker run --rm -v "$PWD:/w" -w /w {container} dafny verify {file}

module {module} {{
'''


def _module(name: str) -> str:
    return "".join(w.capitalize() for w in name.split("_"))


def _dafny_type(t: str) -> str:
    """Translate spec type to Dafny.

    Dafny is simpler than Lean: bounded integer domains like
    Lean's `Fin W` don't have a direct equivalent, so we coerce
    them to `nat` with an implicit upper-bound invariant (users
    add a `requires field < W` on consumers). Function types over
    a `Fin W` domain become `seq<real>` of length W.
    """
    if t == "real":
        return "real"
    if t == "nat":
        return "nat"
    if t.startswith("Fin "):
        return "nat"
    if "->" in t:
        return "seq<real>"
    return t


def compile_dafny(spec: "Spec", out_dir: Path) -> list[Path]:
    """Compile a spec's dafny backend output."""
    dafny_dir = out_dir / "dafny"
    dafny_dir.mkdir(parents=True, exist_ok=True)
    module = _module(spec.protocol.name)
    file_name = f"{module}.dfy"
    path = dafny_dir / file_name

    container = (
        spec.verifiers.dafny.container
        if spec.verifiers.dafny
        else "ghcr.io/athanor-ai/dafny-base:2026.04.10"
    )

    lines = [HEADER.format(
        name=spec.protocol.name,
        citation=spec.protocol.citation or "(no citation)",
        container=container,
        file=file_name,
        module=module,
    )]

    lines.append("  datatype AckEvent = AckEvent(")
    lines.append("    burstSize: nat, delivered: nat, wallClock: real)")
    lines.append("")

    lines.append("  datatype State = State(")
    param_lines = [
        f"    {f.name}: {_dafny_type(f.type)}" for f in spec.protocol.state
    ]
    lines.append(",\n".join(param_lines))
    lines.append("  )")
    lines.append("")

    lines.append("  ghost predicate WellFormed(s: State) {")
    lines.append("    true  // telos: insert invariants in docs/retrofits/<spec>.md")
    lines.append("  }")
    lines.append("")

    for sub in spec.protocol.substeps:
        lines.append(f"  // sub-step: {sub.name}; modifies: {', '.join(sub.modifies) or '(none)'}")
        lines.append(f"  function {sub.name.title().replace('_','')}(s: State, a: AckEvent): State")
        lines.append("    requires WellFormed(s)")
        lines.append("    ensures WellFormed(" + sub.name.title().replace('_','') + "(s, a))")
        lines.append("  {")
        if sub.inline_dafny:
            lines.append(f"    {sub.inline_dafny}")
        else:
            lines.append("    s  // TODO: wire inline body")
        lines.append("  }")
        lines.append("")

    for thm in spec.theorems:
        lines.append(f"  // Theorem: {thm.name} ({thm.kind})")
        if thm.doc:
            for line in thm.doc.strip().splitlines():
                lines.append(f"  // {line}")
        lines.append(f"  lemma {thm.name.title().replace('_','')}()")
        for i, h in enumerate(thm.hypotheses):
            lines.append(f"    // requires {h}")
        lines.append(f"    // ensures {thm.conclusion}")
        lines.append("  {")
        lines.append("    // telos v0.2 emits the lemma skeleton; proof body left for the user.")
        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")

    path.write_text("\n".join(lines))
    return [path]
