"""ebmc backend — emit SystemVerilog + SVA for EBMC k-induction.

Given a Spec, produces:
    build/sv/<protocol>_trace.sv       — always_ff of the step function
    build/sv/<protocol>_invariants.sv  — SVA wrapper + assume gates
    build/sv/run.sh                    — EBMC k-induction + BMC commands

The v0.2 emitter targets the concrete-tuple regime EBMC handles
cleanly (small W, small bitwidth). The spec's
ebmc.concrete_tuple field supplies the parameters; the emitter
scales bitwidths + fills in assume properties accordingly.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


HEADER_TRACE = '''\
// Auto-generated by telos from a declarative spec.
// Do NOT edit by hand; re-run `telos compile` to regenerate.
//
// Protocol: {name}
// Concrete tuple: W={W}, D={D}, B={B}
// Step composition: {steps}

`default_nettype none

module {mod}_trace #(
  parameter int W      = {W},
  parameter int D      = {D},
  parameter int B      = {B},
  parameter int RATE_W = 16
) (
  input  logic                  clk,
  input  logic                  reset,
  input  logic [7:0]            burst_size,
  input  logic [RATE_W-1:0]     delivered,
  input  logic [3:0]            wall_clock,

  output logic [RATE_W-1:0]     pacing_rate,
  output logic [7:0]            tick
);

  initial begin
    pacing_rate = RATE_W'(1);
    tick        = '0;
  end

  always_ff @(posedge clk) begin
    if (reset) begin
      pacing_rate <= RATE_W'(1);
      tick        <= '0;
    end else begin
      // telos v0.2 emits a placeholder update. Replace with the
      // concrete step function for your spec.
      pacing_rate <= pacing_rate;
      if (tick != 8'hFF) tick <= tick + 8'd1;
    end
  end

endmodule
'''


HEADER_INV = '''\
// Auto-generated by telos from a declarative spec.
// SVA wrapper for the {name} trace.

`default_nettype none

module {mod}_invariants;

  localparam int W      = {W};
  localparam int D      = {D};
  localparam int B      = {B};
  localparam int RATE_W = 16;

  logic              clk = 0;
  logic              reset;
  logic [7:0]        burst_size;
  logic [RATE_W-1:0] delivered;
  logic [3:0]        wall_clock;

  logic [RATE_W-1:0] pacing_rate;
  logic [7:0]        tick;

  {mod}_trace #(.W(W), .D(D), .B(B), .RATE_W(RATE_W)) dut (
    .clk(clk), .reset(reset),
    .burst_size(burst_size),
    .delivered(delivered),
    .wall_clock(wall_clock),
    .pacing_rate(pacing_rate),
    .tick(tick)
  );

  // Scheduler assumptions.
  a_burst_bounded: assume property (@(posedge clk)
    burst_size <= 8'(B) && burst_size >= 8'd1);
  a_delivered_bounded: assume property (@(posedge clk)
    delivered <= RATE_W'(B * D));
  a_wall_bounded: assume property (@(posedge clk)
    wall_clock <= 4'd3);
  a_reset_once: assume property (@(posedge clk)
    (tick == '0) |-> reset);
  a_no_reset_after: assume property (@(posedge clk)
    (tick > '0) |-> !reset);

'''


RUN_SH = '''\
#!/usr/bin/env bash
# Auto-generated by telos.
# Runs EBMC k-induction + BMC on the emitted SVA.
set -euo pipefail

ebmc --k-induction --bound {bmc_bound} {mod}_invariants.sv {mod}_trace.sv \\
  | tee ebmc_k_induction.log

ebmc --bound {bmc_bound} {mod}_invariants.sv {mod}_trace.sv \\
  | tee ebmc_bmc_bound{bmc_bound}.log
'''


def compile_ebmc(spec: "Spec", out_dir: Path) -> list[Path]:
    """Compile a spec's ebmc backend output."""
    sv_dir = out_dir / "sv"
    sv_dir.mkdir(parents=True, exist_ok=True)

    if spec.verifiers.ebmc is None:
        return []
    tup = spec.verifiers.ebmc.concrete_tuple
    W, D, B = tup.get("W", 4), tup.get("D", 2), tup.get("B", 7)
    bmc_bound = spec.verifiers.ebmc.bmc_bound

    mod = spec.protocol.name.replace("-", "_")
    steps = " -> ".join(spec.protocol.step_compose) or "(none)"

    trace_path = sv_dir / f"{mod}_trace.sv"
    trace_path.write_text(HEADER_TRACE.format(
        name=spec.protocol.name, mod=mod,
        W=W, D=D, B=B, steps=steps,
    ))

    inv_lines = [HEADER_INV.format(
        name=spec.protocol.name, mod=mod, W=W, D=D, B=B,
    )]
    # Emit one SVA assertion per theorem, best-effort.
    for thm in spec.theorems:
        prop = _theorem_to_sva(thm)
        if prop:
            inv_lines.append(f"  {thm.name}: assert property (")
            inv_lines.append("    @(posedge clk) disable iff (reset)")
            inv_lines.append(f"    {prop}")
            inv_lines.append("  );")
            inv_lines.append("")
    inv_lines.append("endmodule")
    inv_lines.append("")
    inv_path = sv_dir / f"{mod}_invariants.sv"
    inv_path.write_text("\n".join(inv_lines))

    run_path = sv_dir / "run.sh"
    run_path.write_text(RUN_SH.format(mod=mod, bmc_bound=bmc_bound))
    run_path.chmod(0o755)

    return [trace_path, inv_path, run_path]


def _theorem_to_sva(thm) -> str | None:
    """Translate a theorem conclusion into an SVA property where
    possible. v0.2: handles a small vocabulary; falls back to None
    (skipping the assertion emission) for expressions beyond the
    scope."""
    # Handle both "pacing_rate > 0" positive shape and list-form
    # conclusions.
    concl = thm.conclusion
    if isinstance(concl, list):
        concl = concl[0] if concl else ""
    if "pacing_rate" in concl and ">" in concl and "0" in concl:
        return "pacing_rate > '0"
    if "pacing_rate" in concl and ">=" in concl and "1" in concl:
        return "pacing_rate >= '1"
    return None
