"""lean4 backend — emit a Lean 4 project from a telos spec.

Given a Spec, produces:
    build/lean/lakefile.lean
    build/lean/lean-toolchain
    build/lean/<namespace>/Basic.lean     — state + param types
    build/lean/<namespace>/Trace.lean     — step function + Trace struct
    build/lean/<namespace>/Theorem.lean   — theorem statements (sorry-filled)

A hand-written proof may live alongside the generated files as
`<namespace>/TheoremProof.lean` and be imported; the emitter never
overwrites user-authored proof files.

Backend status: v0.2 minimal. Emits the Basic + Theorem skeletons;
Trace is TODO (sub-step composition requires more schema richness
than v0.1 exposes).
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


LAKEFILE = '''\
import Lake
open Lake DSL

package {pkg} where
  leanOptions := #[
    ⟨`pp.unicode.fun, true⟩,
    ⟨`autoImplicit, false⟩
  ]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v{mathlib}"

@[default_target]
lean_lib «{lib}» where
  roots := #[`{lib}.Basic, `{lib}.Trace, `{lib}.Theorem]
'''


HEADER_BASIC = '''\
/-
  Auto-generated by telos from a declarative spec.
  Do NOT edit by hand; re-run `telos compile` to regenerate.

  Protocol: {name}
  Citation: {citation}
-/
import Mathlib.Data.Real.Basic

namespace {namespace}

'''


def _ns(protocol_name: str) -> str:
    """Convert a protocol name to a Lean-safe namespace."""
    return "".join(w.capitalize() for w in protocol_name.split("_"))


def _lean_type(t: str) -> str:
    """Translate a spec type string to a Lean type expression.

    Capitalises primitive type names (real→Real, nat→Nat) — Lean is
    case-sensitive and our YAML convention is lowercase for brevity.
    Complex types (e.g., "Fin W -> real") get component-wise fixups.
    """
    mapping = {"real": "Real", "nat": "Nat"}
    # Word-boundary replace to avoid corrupting "Real" inside compound types.
    import re
    for k, v in mapping.items():
        t = re.sub(rf"\b{k}\b", v, t)
    return t


def emit_basic(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Basic.lean: state + param types."""
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Basic.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [HEADER_BASIC.format(
        name=spec.protocol.name,
        citation=spec.protocol.citation or "(no citation)",
        namespace=ns,
    )]

    lines.append("/-- Parameters of the protocol (fixed across a trace). -/")
    lines.append("structure PathParams where")
    for p in spec.protocol.params:
        lines.append(f"  {p.name} : {_lean_type(p.type)}")
        if p.doc:
            lines[-1] += f"  -- {p.doc}"
    lines.append("  deriving Repr")
    lines.append("")

    # W-parameterised state (most CC protocols use a Fin W filter; if
    # the state mentions `W` we assume a Nat parameter).
    state_uses_W = any("W" in f.type for f in spec.protocol.state)
    W_param = " (W : Nat)" if state_uses_W else ""
    lines.append("/-- Finite-state abstraction of the protocol. -/")
    lines.append(f"structure State{W_param} where")
    for f in spec.protocol.state:
        lines.append(f"  {f.name} : {_lean_type(f.type)}")
        if f.doc:
            lines[-1] += f"  -- {f.doc}"
    lines.append("")

    lines.append(f"end {ns}")
    lines.append("")

    path.write_text("\n".join(lines))
    return path


HEADER_THEOREM = '''\
/-
  Auto-generated by telos — theorem signatures only.
  Proofs live in a sibling file (`TheoremProof.lean`) that imports
  this module and closes each sorry.

  Protocol: {name}
-/
import {namespace}.Basic
import {namespace}.Trace

namespace {namespace}

'''


def emit_theorem(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Theorem.lean: signatures with sorry bodies."""
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Theorem.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [HEADER_THEOREM.format(
        name=spec.protocol.name,
        namespace=ns,
    )]

    for thm in spec.theorems:
        if thm.doc:
            for line in thm.doc.strip().splitlines():
                lines.append(f"/-- {line} -/")
        lines.append(f"theorem {thm.name}")
        for i, h in enumerate(thm.hypotheses):
            lines.append(f"    (h{i} : {h})")
        lines.append(f"    : {thm.conclusion} := by")
        lines.append("  sorry")
        lines.append("")

    lines.append(f"end {ns}")
    lines.append("")

    path.write_text("\n".join(lines))
    return path


def emit_trace(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Trace.lean: step function + Trace struct.

    v0.2 minimal: declares noncomputable step functions pointing to
    the spec's inline_lean bodies. Users may override manually.
    """
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Trace.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [HEADER_BASIC.format(
        name=spec.protocol.name,
        citation=spec.protocol.citation or "(no citation)",
        namespace=ns,
    )]
    lines.append(f"import {ns}.Basic")
    lines.append("")
    lines.append("/-- One ACK event visible to the sender. -/")
    lines.append("structure AckEvent where")
    lines.append("  burst_size : Nat")
    lines.append("  delivered  : Nat")
    lines.append("  wall_clock : Real")
    lines.append("  deriving Repr")
    lines.append("")

    for sub in spec.protocol.substeps:
        body = sub.inline_lean or "sorry"
        lines.append(f"/-- Sub-step: {sub.name}. Modifies: {', '.join(sub.modifies) or '(none)'}. -/")
        lines.append(f"noncomputable def {sub.name} (s : State) (a : AckEvent) : State :=")
        lines.append(f"  -- inline_lean: {body}")
        lines.append(f"  s  -- TODO: wire inline body")
        lines.append("")

    lines.append("/-- One full step of the protocol state machine. -/")
    lines.append("noncomputable def step (s : State) (a : AckEvent) : State :=")
    for sub in spec.protocol.step_compose:
        pass  # let-chain composition placeholder
    lines.append("  -- composed: " + " >>= ".join(spec.protocol.step_compose))
    lines.append("  s  -- TODO")
    lines.append("")

    lines.append(f"end {ns}")
    lines.append("")
    path.write_text("\n".join(lines))
    return path


def emit_lakefile(spec: "Spec", out_dir: Path) -> Path:
    """Emit lakefile.lean at the root."""
    out_dir.mkdir(parents=True, exist_ok=True)
    ns = _ns(spec.protocol.name)
    pkg = spec.protocol.name.replace("_", "-")
    path = out_dir / "lakefile.lean"
    mathlib_pin = "4.14.0"
    path.write_text(LAKEFILE.format(pkg=pkg, mathlib=mathlib_pin, lib=ns))
    toolchain = out_dir / "lean-toolchain"
    if spec.verifiers.lean4:
        tc = spec.verifiers.lean4.toolchain
    else:
        tc = "leanprover/lean4:v4.14.0"
    toolchain.write_text(tc + "\n")
    return path


def compile_lean4(spec: "Spec", out_dir: Path) -> list[Path]:
    """Compile a spec's lean4 backend outputs.

    Returns the list of emitted file paths.
    """
    lean_dir = out_dir / "lean"
    artefacts = [
        emit_lakefile(spec, lean_dir),
        emit_basic(spec, lean_dir),
        emit_trace(spec, lean_dir),
        emit_theorem(spec, lean_dir),
    ]
    return artefacts
