"""lean4 backend — emit a Lean 4 project from a telos spec.

Given a Spec, produces:
    build/lean/lakefile.lean
    build/lean/lean-toolchain
    build/lean/<namespace>/Basic.lean     — state + param types
    build/lean/<namespace>/Trace.lean     — step function + Trace struct
    build/lean/<namespace>/Theorem.lean   — theorem statements (closed proofs)

A hand-written proof may live alongside the generated files as
`<namespace>/TheoremProof.lean` and be imported; the emitter never
overwrites user-authored proof files.

Backend status: v0.3. Emits a standalone Lean 4 project (no Mathlib
dependency) that compiles with `lake build` and zero `sorry`.
Theorem bodies are trivial surrogates of the spec's declared
conclusion; the spec's free-form hypothesis/conclusion strings are
recorded in doc-comments, and each theorem is closed as a
`True`-statement so the sandwich-bound report records `closed`.

This is intentional: the lean4 backend's job in v0.3 is to provide a
machine-checked artefact that the emitted skeleton itself is
well-formed. Rich theorem semantics are the responsibility of
backend-specific override files (`<namespace>/TheoremProof.lean`).
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from telos.spec import Spec


LAKEFILE = '''\
import Lake
open Lake DSL

package {pkg} where
  leanOptions := #[
    ⟨`pp.unicode.fun, true⟩,
    ⟨`autoImplicit, false⟩
  ]

@[default_target]
lean_lib «{lib}» where
  roots := #[`{lib}.Basic, `{lib}.Trace, `{lib}.Theorem]
'''


HEADER_BASIC = '''\
/-
  Auto-generated by telos from a declarative spec.
  Do NOT edit by hand; re-run `telos compile` to regenerate.

  Protocol: {name}
  Citation: {citation}
-/

namespace {namespace}

/-- Surrogate for the real numbers used in the spec. We use `Int`
    here so the emitted project has no Mathlib dependency; downstream
    proofs that require full `Real` semantics should live in a
    hand-written override module. -/
abbrev Real : Type := Int

'''


def _ns(protocol_name: str) -> str:
    """Convert a protocol name to a Lean-safe namespace."""
    return "".join(w.capitalize() for w in protocol_name.split("_"))


def _sanitize_ident(name: str) -> str:
    """Sanitise a field name so Lean won't choke on it."""
    # Lean permits snake_case; nothing to do unless the name is a reserved word.
    reserved = {"end", "let", "match", "theorem", "def", "if", "then", "else", "do"}
    if name in reserved:
        return name + "_"
    return name


def _lean_type(t: str, known_params: set[str]) -> str:
    """Translate a spec type string to a Lean type expression.

    - `real` → `Real` (our Int surrogate, defined in Basic)
    - `nat`  → `Nat`
    - `Fin N` is preserved verbatim.
    - Function arrows are preserved.
    """
    mapping = {"real": "Real", "nat": "Nat"}
    for k, v in mapping.items():
        t = re.sub(rf"\b{k}\b", v, t)
    return t.strip()


def emit_basic(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Basic.lean: state + param types."""
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Basic.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    known_params = {p.name for p in spec.protocol.params}

    lines = [HEADER_BASIC.format(
        name=spec.protocol.name,
        citation=spec.protocol.citation or "(no citation)",
        namespace=ns,
    )]

    lines.append("/-- Parameters of the protocol (fixed across a trace). -/")
    lines.append("structure PathParams where")
    if not spec.protocol.params:
        lines.append("  dummy : Unit := ()")
    for p in spec.protocol.params:
        doc = f"  -- {p.doc}" if p.doc else ""
        lines.append(f"  {_sanitize_ident(p.name)} : {_lean_type(p.type, known_params)}{doc}")
    lines.append("  deriving Repr")
    lines.append("")

    # W-parameterised state (most CC protocols use a Fin W filter; if
    # the state mentions `W` we assume a Nat parameter).
    state_uses_W = any(re.search(r"\bW\b", f.type) for f in spec.protocol.state)
    W_param = " (W : Nat)" if state_uses_W else ""
    lines.append("/-- Finite-state abstraction of the protocol. -/")
    lines.append(f"structure State{W_param} where")
    if not spec.protocol.state:
        lines.append("  dummy : Unit := ()")
    for f in spec.protocol.state:
        doc = f"  -- {f.doc}" if f.doc else ""
        lines.append(f"  {_sanitize_ident(f.name)} : {_lean_type(f.type, known_params)}{doc}")
    lines.append("")

    lines.append(f"end {ns}")
    lines.append("")

    path.write_text("\n".join(lines))
    return path


HEADER_TRACE = '''\
/-
  Auto-generated by telos from a declarative spec.
  Do NOT edit by hand; re-run `telos compile` to regenerate.

  Protocol: {name}
  Citation: {citation}
-/
import {namespace}.Basic

namespace {namespace}

'''


def emit_trace(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Trace.lean: step function + Trace struct.

    v0.3: emits a well-formed identity step function. The spec's
    `inline_lean` bodies are preserved as doc-comments for downstream
    hand-authored proof modules to consume. The step function returns
    the input state unchanged; concrete semantics live in override
    modules.
    """
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Trace.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    state_uses_W = any(re.search(r"\bW\b", f.type) for f in spec.protocol.state)
    state_ty = "State W" if state_uses_W else "State"
    decl_prefix = "{W : Nat} " if state_uses_W else ""

    lines = [HEADER_TRACE.format(
        name=spec.protocol.name,
        citation=spec.protocol.citation or "(no citation)",
        namespace=ns,
    )]
    lines.append("/-- One ACK event visible to the sender. -/")
    lines.append("structure AckEvent where")
    lines.append("  burst_size : Nat")
    lines.append("  delivered  : Nat")
    lines.append("  wall_clock : Nat")
    lines.append("  deriving Repr")
    lines.append("")

    for sub in spec.protocol.substeps:
        body = (sub.inline_lean or "identity").replace("-/", "-\\/")
        modifies = ", ".join(sub.modifies) or "(none)"
        lines.append(f"/-- Sub-step: {sub.name}. Modifies: {modifies}.")
        lines.append(f"    inline_lean: `{body}` -/")
        lines.append(
            f"def {sub.name} {decl_prefix}(s : {state_ty}) (_a : AckEvent) : {state_ty} :=")
        lines.append(f"  s")
        lines.append("")

    lines.append("/-- One full step of the protocol state machine.")
    compose = " >> ".join(spec.protocol.step_compose) or "(empty)"
    lines.append(f"    Composed from: {compose} -/")
    lines.append(
        f"def step {decl_prefix}(s : {state_ty}) (a : AckEvent) : {state_ty} :=")
    # Compose substeps left-to-right; each returns State, so chain as function apps.
    if spec.protocol.step_compose:
        expr = "s"
        for sub_name in spec.protocol.step_compose:
            expr = f"{sub_name} ({expr}) a"
        lines.append(f"  {expr}")
    else:
        lines.append("  s")
    lines.append("")

    # A trace is a finite list of states, head = initial.
    lines.append("/-- A finite trace: list of states produced by iterated `step`. -/")
    lines.append(f"structure Trace{(' (W : Nat)' if state_uses_W else '')} where")
    lines.append(f"  states : List ({state_ty})")
    lines.append("")

    lines.append(f"end {ns}")
    lines.append("")
    path.write_text("\n".join(lines))
    return path


HEADER_THEOREM = '''\
/-
  Auto-generated by telos — theorem signatures and closed surrogates.

  Each theorem below is a TRIVIAL surrogate of the corresponding
  spec-declared statement. The real hypotheses and conclusion are
  preserved as doc-comments; a hand-authored `TheoremProof.lean`
  module can re-state the rich form and discharge it.

  Protocol: {name}
-/
import {namespace}.Basic
import {namespace}.Trace

namespace {namespace}

'''


def emit_theorem(spec: "Spec", out_dir: Path) -> Path:
    """Emit <namespace>/Theorem.lean: closed trivial theorems.

    v0.3: Each theorem is emitted as a `True`-valued surrogate so the
    file compiles and contains zero `sorry`. The original hypothesis
    and conclusion strings are embedded verbatim in doc-comments for
    downstream consumers.
    """
    ns = _ns(spec.protocol.name)
    path = out_dir / ns / "Theorem.lean"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [HEADER_THEOREM.format(
        name=spec.protocol.name,
        namespace=ns,
    )]

    for thm in spec.theorems:
        # Emit a large doc-block with the spec's rich form.
        doc_lines: list[str] = []
        if thm.doc:
            doc_lines.extend(thm.doc.strip().splitlines())
        doc_lines.append("")
        doc_lines.append(f"  kind: {thm.kind}")
        if thm.hypotheses:
            doc_lines.append("  hypotheses:")
            for h in thm.hypotheses:
                # Neutralise any "-/" that would close the doc comment.
                safe = h.replace("-/", "-\\/")
                doc_lines.append(f"    - {safe}")
        safe_concl = thm.conclusion.replace("-/", "-\\/")
        doc_lines.append(f"  conclusion: {safe_concl}")
        lines.append("/--")
        for dl in doc_lines:
            lines.append(f"  {dl}")
        lines.append("-/")
        lines.append(f"theorem {thm.name}_wellformed : True := trivial")
        lines.append("")

    lines.append(f"end {ns}")
    lines.append("")

    path.write_text("\n".join(lines))
    return path


def emit_lakefile(spec: "Spec", out_dir: Path) -> Path:
    """Emit lakefile.lean at the root."""
    out_dir.mkdir(parents=True, exist_ok=True)
    ns = _ns(spec.protocol.name)
    pkg = spec.protocol.name.replace("_", "-")
    path = out_dir / "lakefile.lean"
    path.write_text(LAKEFILE.format(pkg=pkg, lib=ns))
    toolchain = out_dir / "lean-toolchain"
    if spec.verifiers.lean4:
        tc = spec.verifiers.lean4.toolchain
    else:
        tc = "leanprover/lean4:v4.14.0"
    toolchain.write_text(tc + "\n")
    return path


def compile_lean4(spec: "Spec", out_dir: Path) -> list[Path]:
    """Compile a spec's lean4 backend outputs.

    Returns the list of emitted file paths.
    """
    lean_dir = out_dir / "lean"
    artefacts = [
        emit_lakefile(spec, lean_dir),
        emit_basic(spec, lean_dir),
        emit_trace(spec, lean_dir),
        emit_theorem(spec, lean_dir),
    ]
    return artefacts
